ERROR:root:Exception in main()
Traceback (most recent call last):
  File "<ipython-input-97-e63ec437ddd9>", line 14, in <module>
    exit(main())
NameError: name 'main' is not defined
